In [4]:
import pandas as pd

In [5]:
import sklearn
print(pd.__version__, sklearn.__version__)

3.0.6 1.9.1

In [6]:
df = pd.read_csv("../data/raw/NOM_DU_FICHIER.csv", low_memory=False)
print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/NOM_DU_FICHIER.csv'

In [7]:
df = pd.read_csv("../data/raw/2025_LoL_esports_match_data_from_OraclesElixir.csv", low_memory=False)
print(df.shape)
df.head()

(120528, 165)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,200.0,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,157.0,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,241.0,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,257.0,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,20.0,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0

In [8]:
df.shape

(120528, 165)

In [9]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'url',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'dragons (type unknown)',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'atakhans',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [10]:
# 1. Combien de types de lignes ?
print(df["position"].value_counts())

# 2. Complétude des données
print(df["datacompleteness"].value_counts())

# 3. Répartition par ligue (les 15 premières)
print(df["league"].value_counts().head(15))

# 4. Période couverte
print(df["date"].min(), df["date"].max())

# 5. Ta future cible
print(df["result"].value_counts())

position
top     20088
jng     20088
mid     20088
bot     20088
sup     20088
team    20088
Name: count, dtype: int64
datacompleteness
complete    110688
partial       9840
Name: count, dtype: int64
league
LPL       9660
LCK       6660
LCKC      6504
LAS       5844
EM        5268
LJL       4488
LFL       3816
LEC       3696
PCS       3624
PRM       3612
CD        3612
AL        3516
LCP       3492
NACL      3300
LVP SL    3168
Name: count, dtype: int64
2025-01-11 11:11:24 2025-12-29 10:52:27
result
0    60264
1    60264
Name: count, dtype: int64

In [11]:
teams = df[df["position"] == "team"].copy()
print(teams.shape)
teams[["gameid", "date", "league", "teamname", "side", "result"]].head(10)

(20088, 165)

,gameid,date,league,teamname,side,result
10,LOLTMNT03_179647,2025-01-11 11:11:24,LFL2,IziDream,Blue,0
11,LOLTMNT03_179647,2025-01-11 11:11:24,LFL2,Team Valiant,Red,1
22,LOLTMNT06_96134,2025-01-11 12:06:37,LFL2,Esprit Shōnen,Blue,1
23,LOLTMNT06_96134,2025-01-11 12:06:37,LFL2,Skillcamp,Red,0
34,LOLTMNT06_95160,2025-01-11 13:07:47,LFL2,Karmine Corp Blue Stars,Blue,0
35,LOLTMNT06_95160,2025-01-11 13:07:47,LFL2,Project Conquerors,Red,1
46,LOLTMNT03_178705,2025-01-11 14:03:27,LFL2,Zerance,Blue,0
47,LOLTMNT03_178705,2025-01-11 14:03:27,LFL2,Lille Esport,Red,1
58,11715-11715_game_1,2025-01-12 09:24:17,LPL,Weibo Gaming,Blue,1
59,11715-11715_game_1,2025-01-12 09:24:17,LPL,Oh My God,Red,0

In [12]:
teams.shape[0] / 2

10044.0

In [13]:
teams[teams["side"] == "Blue"]["result"].mean()

np.float64(0.5328554360812425)

In [14]:
print(df["league"].value_counts())

league
LPL          9660
LCK          6660
LCKC         6504
LAS          5844
EM           5268
LJL          4488
LFL          3816
LEC          3696
PCS          3624
PRM          3612
CD           3612
AL           3516
LCP          3492
NACL         3300
LVP SL       3168
NLC          3000
TCL          2880
RL           2868
LFL2         2796
LTA S        2664
HLL          2652
LTA N        2568
ROL          2496
HC           2400
EBL          2292
HM           2280
AM           2124
LPLOL        1896
NEXO         1848
LRN          1812
VCS          1692
LIT          1668
LRS          1632
HW           1368
WLDs         1152
MSI           960
DCup          936
PRMP          876
KeSPA Cup     672
CT            600
ASI           504
LTA           480
FST           420
EWC           396
IC            336
Name: count, dtype: int64

In [ ]:
print(df["league"].value_counts())

league
LPL          9660
LCK          6660
LCKC         6504
LAS          5844
EM           5268
LJL          4488
LFL          3816
LEC          3696
PCS          3624
PRM          3612
CD           3612
AL           3516
LCP          3492
NACL         3300
LVP SL       3168
NLC          3000
TCL          2880
RL           2868
LFL2         2796
LTA S        2664
HLL          2652
LTA N        2568
ROL          2496
HC           2400
EBL          2292
HM           2280
AM           2124
LPLOL        1896
NEXO         1848
LRN          1812
VCS          1692
LIT          1668
LRS          1632
HW           1368
WLDs         1152
MSI           960
DCup          936
PRMP          876
KeSPA Cup     672
CT            600
ASI           504
LTA           480
FST           420
EWC           396
IC            336
Name: count, dtype: int64

In [15]:
print(df["year"].value_counts().sort_index())
print(df["date"].min(), df["date"].max())

year
2025    117552
2026      2976
Name: count, dtype: int64
2025-01-11 11:11:24 2025-12-29 10:52:27

In [16]:
# Nombre de PARTIES par ligue (liste complète, sans troncature)
print(df.groupby("league")["gameid"].nunique().sort_values(ascending=False).to_string())

# Période couverte
print(df["year"].value_counts().sort_index())
print(df["date"].min(), df["date"].max())

league
LPL          805
LCK          555
LCKC         542
LAS          487
EM           439
LJL          374
LFL          318
LEC          308
PCS          302
CD           301
PRM          301
AL           293
LCP          291
NACL         275
LVP SL       264
NLC          250
TCL          240
RL           239
LFL2         233
LTA S        222
HLL          221
LTA N        214
ROL          208
HC           200
EBL          191
HM           190
AM           177
LPLOL        158
NEXO         154
LRN          151
VCS          141
LIT          139
LRS          136
HW           114
WLDs          96
MSI           80
DCup          78
PRMP          73
KeSPA Cup     56
CT            50
ASI           42
LTA           40
FST           35
EWC           33
IC            28
year
2025    117552
2026      2976
Name: count, dtype: int64
2025-01-11 11:11:24 2025-12-29 10:52:27

In [17]:
print(sorted(df["league"].unique()))

['AL', 'AM', 'ASI', 'CD', 'CT', 'DCup', 'EBL', 'EM', 'EWC', 'FST', 'HC', 'HLL', 'HM', 'HW', 'IC', 'KeSPA Cup', 'LAS', 'LCK', 'LCKC', 'LCP', 'LEC', 'LFL', 'LFL2', 'LIT', 'LJL', 'LPL', 'LPLOL', 'LRN', 'LRS', 'LTA', 'LTA N', 'LTA S', 'LVP SL', 'MSI', 'NACL', 'NEXO', 'NLC', 'PCS', 'PRM', 'PRMP', 'RL', 'ROL', 'TCL', 'VCS', 'WLDs']

In [18]:
teams = df[df["position"] == "team"].copy()
teams["date"] = pd.to_datetime(teams["date"])
print(teams.groupby(teams["date"].dt.to_period("M"))["gameid"].nunique())
print(teams[teams["year"] == 2026][["date", "league", "split"]].drop_duplicates().head())

date
2025-01     518
2025-02    1048
2025-03     709
2025-04    1626
2025-05    1626
2025-06     717
2025-07     885
2025-08    1349
2025-09     826
2025-10     512
2025-11      94
2025-12     134
Freq: M, Name: gameid, dtype: int64
                     date league   split
83926 2025-07-29 15:10:01    HLL  Winter
83974 2025-07-29 16:05:11    HLL  Winter
84010 2025-07-29 16:18:33    HLL  Winter
84058 2025-07-29 16:59:54    HLL  Winter
84082 2025-07-29 17:17:35    HLL  Winter

In [ ]:
print(sorted(df["league"].unique()))

['AL', 'AM', 'ASI', 'CD', 'CT', 'DCup', 'EBL', 'EM', 'EWC', 'FST', 'HC', 'HLL', 'HM', 'HW', 'IC', 'KeSPA Cup', 'LAS', 'LCK', 'LCKC', 'LCP', 'LEC', 'LFL', 'LFL2', 'LIT', 'LJL', 'LPL', 'LPLOL', 'LRN', 'LRS', 'LTA', 'LTA N', 'LTA S', 'LVP SL', 'MSI', 'NACL', 'NEXO', 'NLC', 'PCS', 'PRM', 'PRMP', 'RL', 'ROL', 'TCL', 'VCS', 'WLDs']

In [19]:
blue = teams[teams["side"] == "Blue"][
    ["gameid", "date", "league", "split", "playoffs", "patch", "teamname", "result"]
].rename(columns={"teamname": "blue_team", "result": "blue_win"})

red = teams[teams["side"] == "Red"][["gameid", "teamname"]].rename(
    columns={"teamname": "red_team"}
)

games = blue.merge(red, on="gameid").sort_values("date").reset_index(drop=True)
print(games.shape)
games.head()

(10044, 9)

,gameid,date,league,split,playoffs,patch,blue_team,blue_win,red_team
0,LOLTMNT03_179647,2025-01-11 11:11:24,LFL2,Winter,0,15.01,IziDream,0,Team Valiant
1,LOLTMNT06_96134,2025-01-11 12:06:37,LFL2,Winter,0,15.01,Esprit Shōnen,1,Skillcamp
2,LOLTMNT06_95160,2025-01-11 13:07:47,LFL2,Winter,0,15.01,Karmine Corp Blue Stars,0,Project Conquerors
3,LOLTMNT03_178705,2025-01-11 14:03:27,LFL2,Winter,0,15.01,Zerance,0,Lille Esport
4,11715-11715_game_1,2025-01-12 09:24:17,LPL,Split 1,0,15.01,Weibo Gaming,1,Oh My God

In [20]:
games.shape

(10044, 9)

In [21]:
games["blue_win"].mean()

np.float64(0.5328554360812425)